# @package _global_
hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    name: ${hydra.job.name}
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j

    partition: Main
    qos: low
    nodes: 1
    cpus_per_task: 6
    timeout_min: 8640
    max_num_timeout: 3
    gres: gpu:2